// Renders tools/dev/kit-preview.html headless (Edge, 1500 px wide, DPR 1) in
// light and dark, runs behaviour + accessibility checks on the calm
// components, and writes screenshots to tools/dev/out/:
//   kit-light.png, kit-dark.png                 shell frame + component sheet (full page)
//   kit-confirm-light.png, kit-confirm-dark.png rs-confirm open (1500x1000)
// Usage: node tools/dev/kit-preview.mjs [--no-checks] [--lang en|de]   (default en)
// Env: RS_PLAYWRIGHT_CORE overrides the playwright-core index.mjs path.
// Exit code 1 if any check fails.
import { pathToFileURL, fileURLToPath } from 'node:url';
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { browserChannel, loadChromium } from './rs-server.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');
const outDir = path.join(here, 'out');
mkdirSync(outDir, { recursive: true });

const langArg = process.argv.indexOf('--lang');
const lang = langArg > 0 && process.argv[langArg + 1] === 'de' ? 'de' : 'en';
const S = JSON.parse(readFileSync(path.join(root, `core/i18n/${lang}.json`), 'utf8'));
const t = (k, p) => S[k].replace(/\{([a-z0-9_]+)\}/g, (m, n) => (p && n in p ? String(p[n]) : m));
const platforms = JSON.parse(readFileSync(path.join(root, 'core/static/platforms.json'), 'utf8'));
writeFileSync(path.join(outDir, 'kit-data.js'),
  '// generated by kit-preview.mjs\nwindow.RS_KIT_DATA = ' + JSON.stringify({ lang, strings: S, platforms }) + ';\n');
// the kit borrows the template list/tab styles read-only (bundled, so no template paths in the kit)
const css = [];
const walk = (d) => { for (const f of readdirSync(d, { withFileTypes: true })) { const p = path.join(d, f.name); if (f.isDirectory()) walk(p); else if (f.name === 'template.css') css.push(readFileSync(p, 'utf8')); } };
walk(path.join(root, 'templates'));
writeFileSync(path.join(outDir, 'kit-templates.css'), '/* generated by kit-preview.mjs */\n' + css.join('\n'));

const AXE_SHA = '20c09fe157a8a34a30e241aaa1fcdade657734f08ab379ecfbeb7d45cc46e878';
const axePath = path.join(root, 'vendor/axe.min.js');
const axeOk = createHash('sha256').update(readFileSync(axePath)).digest('hex') === AXE_SHA;

const chromium = await loadChromium();
if (!chromium) {
  throw new Error('playwright-core not found; set RS_PLAYWRIGHT_CORE');
}
const url = pathToFileURL(path.join(here, 'kit-preview.html')).href;
const checks = process.argv.includes('--no-checks') ? null : [];
function check(name, ok, info) {
  if (!checks) return;
  checks.push({ name, ok: !!ok, info });
}

const browser = await chromium.launch({ channel: browserChannel(), headless: true });

async function openPage(theme) {
  const ctx = await browser.newContext({ viewport: { width: 1500, height: 1000 }, deviceScaleFactor: 1, colorScheme: theme, reducedMotion: 'reduce' });
  const page = await ctx.newPage();
  const errors = [];
  const requests = [];
  page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(m.type() + ': ' + m.text()); });
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
  page.on('request', (r) => requests.push(r.url()));
  await page.clock.install();
  await page.goto(url);
  await page.waitForFunction(() => window.KIT && window.KIT.composed);
  return { ctx, page, errors, requests };
}

for (const theme of ['light', 'dark']) {
  const { ctx, page, errors, requests } = await openPage(theme);

  // resting state, plus one keyboard focus ring on a choice in the sheet
  await page.mouse.move(1495, 995);
  await page.keyboard.press('Shift');
  await page.focus('#row-3 button');
  await page.screenshot({ path: path.join(outDir, `kit-${theme}.png`), fullPage: true });

  // confirm dialog (modal, viewport shot)
  await page.evaluate(() => {
    window.__confirm = document.getElementById('kit-confirm').open({ word: 'DELETE', heading: 'Move the file to the trash?', message: 'example.pdf moves to the trash folder.' });
  });
  await page.keyboard.type('DELE');
  await page.screenshot({ path: path.join(outDir, `kit-confirm-${theme}.png`) });
  await page.keyboard.press('Escape');
  check(`[${theme}] confirm: Esc resolves false`, (await page.evaluate(() => window.__confirm)) === false);

  if (checks) {
    check(`[${theme}] no console errors/warnings`, errors.length === 0, errors);
    const bad = requests.filter((u) => !u.startsWith('file:') && !u.startsWith('data:'));
    check(`[${theme}] only file:/data: requests`, bad.length === 0, bad);
    const type = await page.evaluate(() => {
      const sizes = new Set(), weights = new Set();
      const w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
      let n;
      while ((n = w.nextNode())) {
        const el = n.parentElement;
        if (!n.data.trim() || !el || el.closest('script, style, .rs-vh, [data-rs-mockup], .rs-pf__chrome, dialog') || !el.getClientRects().length) continue;
        if (getComputedStyle(el).visibility === 'hidden') continue;
        sizes.add(getComputedStyle(el).fontSize);
        weights.add(getComputedStyle(el).fontWeight);
      }
      return { sizes: [...sizes].sort(), weights: [...weights].sort() };
    });
    check(`[${theme}] at most 3 font sizes outside mockups (K4)`, type.sizes.length <= 3, type.sizes);
    check(`[${theme}] at most 2 font weights outside mockups (K4)`, type.weights.length <= 2, type.weights);
    const missing = await page.evaluate(() => window.KIT.missing);
    check(`[${theme}] every RS.t key exists in ${lang}.json`, missing.length === 0, missing);
    if (axeOk) {
      await page.addScriptTag({ path: axePath });
      const res = await page.evaluate(async () => {
        const r = await window.axe.run(document, { resultTypes: ['violations'] });
        return r.violations.map((v) => ({ id: v.id, impact: v.impact, n: v.nodes.length, target: v.nodes.slice(0, 3).map((x) => x.target.join(' ')) }));
      });
      const serious = res.filter((v) => v.impact === 'serious' || v.impact === 'critical');
      check(`[${theme}] axe-core: 0 serious/critical`, serious.length === 0, res);
    } else {
      check(`[${theme}] axe-core sha256 matches vendor/README`, false);
    }
  }
  await ctx.close();
}

// ---------------------------------------------------------- behaviour --
if (checks) {
  const { ctx, page } = await openPage('light');
  const ev = (fn, arg) => page.evaluate(fn, arg);

  // rs-action-row (segmented control)
  const r1 = await ev(() => {
    const row = document.getElementById('row-1');
    const b = [...row.querySelectorAll('button')];
    return { role: row.getAttribute('role'), label: row.getAttribute('aria-label'), value: row.value,
      checked: b.map((x) => x.getAttribute('aria-checked')), tab: b.map((x) => x.tabIndex), roles: b.map((x) => x.getAttribute('role')) };
  });
  check('choice: radiogroup with name', r1.role === 'radiogroup' && !!r1.label, r1);
  check('choice: no preselection', r1.value === '' && r1.checked.every((c) => c === 'false'), r1);
  check('choice: roving tabindex starts on first', JSON.stringify(r1.tab) === '[0,-1,-1]', r1.tab);
  check('choice: buttons are radios', r1.roles.every((r) => r === 'radio'), r1.roles);
  await ev(() => { window.__changes = []; document.getElementById('row-1').addEventListener('change', (e) => window.__changes.push(e.detail.value)); });
  await page.focus('#row-1 button');
  await page.keyboard.press('ArrowRight');
  let st = await ev(() => { const row = document.getElementById('row-1'); return { v: row.value, f: document.activeElement.value, tab: [...row.querySelectorAll('button')].map((x) => x.tabIndex) }; });
  check('choice: ArrowRight selects + focuses next', st.v === 'spaeter' && st.f === 'spaeter' && JSON.stringify(st.tab) === '[-1,0,-1]', st);
  await page.keyboard.press('ArrowLeft');
  await page.keyboard.press('ArrowLeft');
  st = await ev(() => document.getElementById('row-1').value);
  check('choice: ArrowLeft wraps around', st === 'ignorieren', st);
  await page.click('#row-1 button[value="spaeter"]');
  await page.click('#row-1 button[value="spaeter"]');
  st = await ev(() => window.__changes);
  check('choice: change events (no duplicate on re-click)', JSON.stringify(st) === '["spaeter","erledigt","ignorieren","spaeter"]', st);
  st = await ev(() => document.getElementById('row-2').value);
  check('choice: value attribute preselects (template restore)', st === 'spaeter', st);
  st = await ev(() => { const b = document.querySelector('#row-1 button[aria-checked="true"]'); const s = getComputedStyle(b); return { bg: s.backgroundColor, accent: getComputedStyle(document.documentElement).getPropertyValue('--rs-accent') }; });
  check('choice: selected segment is neutral, not accent-filled (K1)', !/rgb\(59, 79, 216\)/.test(st.bg), st);

  // focus ring computed >= 2px (keyboard modality first, so :focus-visible applies)
  await page.keyboard.press('Shift');
  await page.focus('#row-3 button');
  st = await ev(() => { const s = getComputedStyle(document.activeElement); return { w: s.outlineWidth, style: s.outlineStyle }; });
  check('focused choice has outline >= 2px', parseFloat(st.w) >= 2 && st.style !== 'none', st);

  // rs-copy: icon-only, hidden in an item until hover/focus
  st = await ev(() => { const b = document.querySelector('#copy-code .rs-copy__btn'); const r = b.getBoundingClientRect(); return { w: r.width, h: r.height, label: b.getAttribute('aria-label'), opacity: getComputedStyle(b).opacity }; });
  check('copy: icon-only <= 32 px with aria-label', st.w <= 32 && st.h <= 32 && st.label === 'Copy code', st);
  await page.mouse.move(1495, 5);
  st = await ev(() => getComputedStyle(document.querySelector('#copy-code .rs-copy__btn')).opacity);
  check('copy: visible at rest (copy-first)', st === '1', st);
  st = await ev(() => [...document.querySelectorAll('#copy-code, #copy-draft, #copy-x')].map((c) => c.querySelector('.rs-copy__btn').tabIndex));
  check('copy: every copy icon is its own tab stop', JSON.stringify(st) === '[0,0,0]', st);
  st = await ev(() => { const c = document.getElementById('copy-draft'); return { tab: c.querySelector('.rs-copy__value').tabIndex, clamp: c.querySelector('.rs-copy__value').classList.contains('rs-copy__value--clamp'), more: !c.querySelector('.rs-copy__more').hidden }; });
  check('copy: long value clamped behind "Show all", no extra tab stop (K2)', st.tab === -1 && st.clamp && st.more, st);
  await ev(() => { window.__copyEv = []; document.addEventListener('rs-copy', (e) => window.__copyEv.push(e.detail)); });
  await page.click('#copy-amount .rs-copy__btn');
  st = await ev(() => { const c = document.getElementById('copy-amount'); return { state: c.dataset.state, value: c.querySelector('.rs-copy__value').textContent, last: window.KIT.copies.at(-1), toast: [...document.querySelectorAll('.rs-toast')].map((x) => x.textContent) }; });
  check('copy: state copied', st.state === 'copied', st);
  check('copy: exact text passed to RS.copy and shown', st.last === '184.20' && st.value === st.last, st);
  check('copy: toast announced', st.toast.includes(S.copied), st.toast);
  await page.clock.runFor(1400);
  st = await ev(() => document.getElementById('copy-amount').dataset.state);
  check('copy: still copied at 1.4 s', st === 'copied', st);
  await page.clock.runFor(200);
  st = await ev(() => document.getElementById('copy-amount').dataset.state);
  check('copy: back to idle after 1.5 s', st === 'idle', st);
  await ev(() => { window.KIT.nextCopy = 'busy'; });
  await page.click('#copy-amount .rs-copy__btn');
  st = await ev(() => { const c = document.getElementById('copy-amount'); return { state: c.dataset.state, msg: c.querySelector('.rs-copy__msg').textContent, hidden: c.querySelector('.rs-copy__msg').hidden }; });
  check('copy: 423 shows the busy message', st.state === 'busy' && !st.hidden && st.msg === S.clipboard_busy, st);
  await page.click('#copy-amount .rs-copy__btn');
  st = await ev(() => { const c = document.getElementById('copy-amount'); return { state: c.dataset.state, hidden: c.querySelector('.rs-copy__msg').hidden, ev: window.__copyEv }; });
  check('copy: retry clears busy message', st.state === 'copied' && st.hidden, st);
  check('copy: rs-copy events', JSON.stringify(st.ev) === '[{"ok":true,"busy":false},{"ok":false,"busy":true},{"ok":true,"busy":false}]', st.ev);
  st = await ev(() => document.querySelector('#copy-x .rs-copy__value').hidden);
  check('copy: no-value hides the value', st === true, st);

  // rs-counter
  st = await ev(() => { const c = document.getElementById('counter-over'); return { over: c.over, num: c.querySelector('.rs-counter__num').textContent, sr: c.querySelector('.rs-vh').textContent }; });
  check('counter: over state + accessible label', st.over && st.num === t('counter_value', { value: '301', limit: '280' }) && st.sr === t('counter_label_over', { value: '301', limit: '280', n: '21' }), st);
  st = await ev(() => { const c = document.getElementById('counter-over'); const d = c.querySelector('.rs-dot'); return { color: getComputedStyle(c).color, ink: getComputedStyle(document.body).color, dot: d && !d.hidden && d.getAttribute('data-rs-status') }; });
  check('counter: over-limit text stays neutral, a status dot carries the hue (K6)', st.color === st.ink && st.dot === 'danger', st);

  // rs-badge status semantics
  st = await ev(() => [...document.querySelectorAll('rs-badge[variant]')].map((b) => [b.getAttribute('variant'), b.getAttribute('data-rs-status')]));
  check('badge: non-neutral variants carry data-rs-status (K6 exception)', st.every(([v, s]) => (v === 'neutral' ? s === null : s === v)), st);

  // rs-post-frame
  st = await ev(() => ['x', 'linkedin', 'instagram', 'facebook'].map((s) => {
    const f = document.querySelector(`rs-post-frame[skin="${s}"]`);
    const note = f.querySelector('.rs-pf__foldnote');
    return { s, mock: f.querySelector('[data-rs-mockup]')?.getAttribute('data-rs-mockup'), chrome: getComputedStyle(f.querySelector('.rs-pf__chrome')).display,
      noChrome: f.hasAttribute('no-chrome'), note: note && !note.hidden,
      label: f.querySelectorAll('.rs-pf__see-more').length, bar: f.querySelectorAll('.rs-pf__fold, .rs-pf__foldnote-bar').length };
  }));
  check('post-frame: preview marked data-rs-mockup', st.every((x) => x.mock === x.s), st);
  check('post-frame: no-chrome hides the logo row', st.every((x) => (x.noChrome ? x.chrome === 'none' : x.chrome !== 'none')), st);
  check('post-frame: fold guides on LinkedIn and Instagram only', st.find((x) => x.s === 'linkedin').note && st.find((x) => x.s === 'instagram').note && !st.find((x) => x.s === 'x').note, st);
  check('post-frame: the fold is an inline platform label, no bar', st.every((x) => x.bar === 0 && x.label === (x.note ? 1 : 0)), st);
  st = await ev(() => Math.round(document.querySelector('#pf-li [data-rs-mockup]').getBoundingClientRect().width));
  check('post-frame: the one preview is >= 480 px wide (K10)', st >= 480, st);

  // tabs
  st = await ev(() => [...document.querySelectorAll('[role="tablist"] [role="tab"]')].map((b) => [b.getAttribute('aria-selected'), b.tabIndex]));
  check('tabs: one selected, roving tabindex', st.filter(([s]) => s === 'true').length === 1 && st.filter(([, i]) => i === 0).length === 1, st);

  // rs-confirm
  await page.focus('#copy-code .rs-copy__btn');
  await ev(() => { window.__c = undefined; document.getElementById('kit-confirm').open({ word: 'DELETE' }).then((v) => { window.__c = v; }); });
  st = await ev(() => { const d = document.querySelector('#kit-confirm dialog'); return { open: d.open, modal: d.matches(':modal'), label: d.querySelector('label').textContent, focus: document.activeElement.className, disabled: d.querySelector('button[type=submit]').disabled }; });
  check('confirm: modal open, label text, focus in input, confirm disabled', st.open && st.modal && st.label === t('confirm_type', { word: 'DELETE' }) && st.focus.includes('rs-confirm__input') && st.disabled, st);
  await page.keyboard.type('delete');
  st = await ev(() => document.querySelector('#kit-confirm button[type=submit]').disabled);
  check('confirm: case differs -> still disabled', st === true);
  await page.fill('#kit-confirm input', 'DELETE');
  st = await ev(() => document.querySelector('#kit-confirm button[type=submit]').disabled);
  check('confirm: exact word enables confirm', st === false);
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => window.__c !== undefined);
  st = await ev(() => ({ c: window.__c, open: document.querySelector('#kit-confirm dialog').open, focus: document.activeElement.closest('rs-copy')?.id }));
  check('confirm: resolves true, closes, returns focus', st.c === true && !st.open && st.focus === 'copy-code', st);

  // global a11y basics
  st = await ev(() => ({
    pos: [...document.querySelectorAll('[tabindex]')].filter((e) => e.tabIndex > 0).length,
    unnamed: [...document.querySelectorAll('button, input, textarea, select')].filter((e) => {
      if (e.closest('dialog:not([open])')) return false;
      const name = (e.getAttribute('aria-label') || e.labels?.[0]?.textContent || e.innerText || e.placeholder || '').trim();
      return !name;
    }).map((e) => e.outerHTML.slice(0, 80)),
  }));
  check('no positive tabindex', st.pos === 0, st.pos);
  check('every control has a name', st.unnamed.length === 0, st.unnamed);
  await ctx.close();
}

await browser.close();

if (checks) {
  let fail = 0;
  for (const c of checks) {
    if (!c.ok) fail++;
    console.log((c.ok ? 'PASS ' : 'FAIL ') + c.name + (c.ok ? '' : '  ' + JSON.stringify(c.info)));
  }
  console.log(`\n${checks.length - fail}/${checks.length} checks passed`);
  console.log('screenshots: ' + outDir);
  process.exit(fail ? 1 : 0);
}
