// Renders tools/dev/kit-preview.html headless (Edge, 1500x1000, DPR 1) in
// light and dark, runs behaviour + accessibility checks on the components,
// and writes screenshots to tools/dev/out/:
//   kit-light.png, kit-dark.png                 both kit frames stacked (1500x2008)
//   kit-confirm-light.png, kit-confirm-dark.png rs-confirm open (1500x1000)
// Usage: node tools/dev/kit-preview.mjs [--no-checks]
// Env: RS_PLAYWRIGHT_CORE overrides the playwright-core index.mjs path.
// Exit code 1 if any check fails.
import { pathToFileURL, fileURLToPath } from 'node:url';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { browserChannel, loadChromium } from './rs-server.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');
const outDir = path.join(here, 'out');
mkdirSync(outDir, { recursive: true });

const strings = JSON.parse(readFileSync(path.join(root, 'core/i18n/de.json'), 'utf8'));
const platforms = JSON.parse(readFileSync(path.join(root, 'core/static/platforms.json'), 'utf8'));
writeFileSync(path.join(outDir, 'kit-data.js'),
  '// generated by kit-preview.mjs\nwindow.RS_KIT_DATA = ' + JSON.stringify({ strings, platforms }) + ';\n');

const AXE_SHA = '20c09fe157a8a34a30e241aaa1fcdade657734f08ab379ecfbeb7d45cc46e878';
const axePath = path.join(root, 'vendor/axe.min.js');
const axeOk = createHash('sha256').update(readFileSync(axePath)).digest('hex') === AXE_SHA;

const chromium = await loadChromium();
if (!chromium) throw new Error('playwright-core not found; install it or set RS_PLAYWRIGHT_CORE');
const url = pathToFileURL(path.join(here, 'kit-preview.html')).href;
const checks = process.argv.includes('--no-checks') ? null : [];
function check(name, ok, info) {
  if (!checks) return;
  checks.push({ name, ok: !!ok, info });
}

const browser = await chromium.launch({ channel: browserChannel(), headless: true });

async function openPage(theme) {
  const ctx = await browser.newContext({ viewport: { width: 1500, height: 1000 }, deviceScaleFactor: 1, colorScheme: theme, reducedMotion: 'reduce' });
  const page = await ctx.newPage();
  const errors = [];
  const requests = [];
  page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(m.type() + ': ' + m.text()); });
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
  page.on('request', (r) => requests.push(r.url()));
  await page.clock.install();
  await page.goto(url);
  await page.waitForFunction(() => window.KIT && window.KIT.composed);
  return { ctx, page, errors, requests };
}

for (const theme of ['light', 'dark']) {
  const { ctx, page, errors, requests } = await openPage(theme);

  // frame 1 states: copied (ok), busy (423), keyboard focus ring on a choice
  await page.click('#copy-amount .rs-copy__btn');
  await page.evaluate(() => { window.KIT.nextCopy = 'busy'; });
  await page.click('#copy-ref .rs-copy__btn');
  await page.keyboard.press('Shift');
  await page.focus('#row-3 button');
  await page.screenshot({ path: path.join(outDir, `kit-${theme}.png`), fullPage: true });

  // confirm dialog (modal, viewport shot)
  await page.evaluate(() => {
    window.__confirm = document.getElementById('kit-confirm').open({ word: 'LÖSCHEN', heading: 'PDF in den Papierkorb?', message: 'rechnung-2026-10-0042.pdf wird nach _trash\\2026-10-08\\ verschoben.' });
  });
  await page.keyboard.type('LÖSCH');
  await page.screenshot({ path: path.join(outDir, `kit-confirm-${theme}.png`) });
  await page.keyboard.press('Escape');
  check(`[${theme}] confirm: Esc resolves false`, (await page.evaluate(() => window.__confirm)) === false);

  if (checks) {
    check(`[${theme}] no console errors/warnings`, errors.length === 0, errors);
    const bad = requests.filter((u) => !u.startsWith('file:') && !u.startsWith('data:'));
    check(`[${theme}] only file:/data: requests`, bad.length === 0, bad);
    const sizes = await page.evaluate(() => {
      const out = new Set();
      const w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
      let n;
      while ((n = w.nextNode())) {
        const el = n.parentElement;
        if (!n.data.trim() || !el || el.closest('script, style, .rs-vh') || !el.getClientRects().length) continue;
        if (getComputedStyle(el).visibility === 'hidden') continue;
        out.add(getComputedStyle(el).fontSize);
      }
      return [...out].sort();
    });
    check(`[${theme}] at most 3 font sizes (U6)`, sizes.length <= 3, sizes);
    const missing = await page.evaluate(() => window.KIT.missing);
    check(`[${theme}] every RS.t key exists in de.json`, missing.length === 0, missing);
    if (axeOk) {
      await page.addScriptTag({ path: axePath });
      const res = await page.evaluate(async () => {
        const r = await window.axe.run(document, { resultTypes: ['violations'] });
        return r.violations.map((v) => ({ id: v.id, impact: v.impact, n: v.nodes.length, target: v.nodes.slice(0, 3).map((x) => x.target.join(' ')) }));
      });
      const serious = res.filter((v) => v.impact === 'serious' || v.impact === 'critical');
      check(`[${theme}] axe-core: 0 serious/critical`, serious.length === 0, res);
    } else {
      check(`[${theme}] axe-core sha256 matches vendor/README`, false);
    }
  }
  await ctx.close();
}

// ---------------------------------------------------------- behaviour --
if (checks) {
  const { ctx, page } = await openPage('light');
  const ev = (fn, arg) => page.evaluate(fn, arg);

  // rs-action-row
  const r1 = await ev(() => {
    const row = document.getElementById('row-1');
    const b = [...row.querySelectorAll('button')];
    return { role: row.getAttribute('role'), label: row.getAttribute('aria-label'), value: row.value,
      checked: b.map((x) => x.getAttribute('aria-checked')), tab: b.map((x) => x.tabIndex), roles: b.map((x) => x.getAttribute('role')) };
  });
  check('action-row: radiogroup with name', r1.role === 'radiogroup' && !!r1.label, r1);
  check('action-row: no preselection', r1.value === '' && r1.checked.every((c) => c === 'false'), r1);
  check('action-row: roving tabindex starts on first', JSON.stringify(r1.tab) === '[0,-1,-1]', r1.tab);
  check('action-row: buttons are radios', r1.roles.every((r) => r === 'radio'), r1.roles);
  await ev(() => { window.__changes = []; document.getElementById('row-1').addEventListener('change', (e) => window.__changes.push(e.detail.value)); });
  await page.focus('#row-1 button');
  await page.keyboard.press('ArrowRight');
  let st = await ev(() => { const row = document.getElementById('row-1'); return { v: row.value, f: document.activeElement.value, tab: [...row.querySelectorAll('button')].map((x) => x.tabIndex) }; });
  check('action-row: ArrowRight selects + focuses next', st.v === 'spaeter' && st.f === 'spaeter' && JSON.stringify(st.tab) === '[-1,0,-1]', st);
  await page.keyboard.press('ArrowLeft');
  await page.keyboard.press('ArrowLeft');
  st = await ev(() => document.getElementById('row-1').value);
  check('action-row: ArrowLeft wraps around', st === 'ignorieren', st);
  await page.keyboard.press('Home');
  await page.click('#row-1 button[value="spaeter"]');
  await page.click('#row-1 button[value="spaeter"]');
  st = await ev(() => window.__changes);
  check('action-row: change events (no duplicate on re-click)', JSON.stringify(st) === '["spaeter","erledigt","ignorieren","erledigt","spaeter"]', st);
  st = await ev(() => document.getElementById('row-2').value);
  check('action-row: value attribute preselects (template restore)', st === 'spaeter', st);

  // Tab order: one stop per radiogroup
  await page.focus('#copy-draft .rs-copy__btn');
  await page.keyboard.press('Tab');
  await page.keyboard.press('Tab');
  st = await ev(() => ({ v: document.activeElement.value, row: document.activeElement.parentElement.id }));
  check('Tab enters a radiogroup at the checked option', st.row === 'row-2' && st.v === 'spaeter', st);
  await page.keyboard.press('Tab');
  st = await ev(() => document.activeElement.tagName);
  check('Tab leaves the radiogroup after one stop', st === 'INPUT', st);

  // focus ring computed >= 2px
  st = await ev(() => { const s = getComputedStyle(document.activeElement); return { w: s.outlineWidth, style: s.outlineStyle }; });
  check('focused input has outline >= 2px', parseFloat(st.w) >= 2 && st.style !== 'none', st);
  await page.focus('#row-3 button');
  st = await ev(() => { const s = getComputedStyle(document.activeElement); return { w: s.outlineWidth, style: s.outlineStyle }; });
  check('focused choice has outline >= 2px', parseFloat(st.w) >= 2 && st.style !== 'none', st);

  // rs-copy
  await ev(() => { window.__copyEv = []; document.addEventListener('rs-copy', (e) => window.__copyEv.push(e.detail)); });
  await page.click('#copy-iban .rs-copy__btn');
  st = await ev(() => { const c = document.getElementById('copy-iban'); return { state: c.dataset.state, text: c.querySelector('.rs-copy__btn').innerText.trim(), value: c.querySelector('.rs-copy__value').textContent, last: window.KIT.copies.at(-1), toast: [...document.querySelectorAll('.rs-toast')].map((x) => x.textContent) }; });
  check('copy: state copied + label "Kopiert ✓"', st.state === 'copied' && st.text === 'Kopiert ✓', st);
  check('copy: exact text passed to RS.copy and shown in full', st.last === 'AT61 1904 3002 3457 3201' && st.value === st.last, st);
  check('copy: toast announced', st.toast.includes('Kopiert ✓'), st.toast);
  await page.clock.runFor(1400);
  st = await ev(() => document.getElementById('copy-iban').dataset.state);
  check('copy: still copied at 1.4 s', st === 'copied', st);
  await page.clock.runFor(200);
  st = await ev(() => document.getElementById('copy-iban').dataset.state);
  check('copy: back to idle after 1.5 s', st === 'idle', st);
  await ev(() => { window.KIT.nextCopy = 'busy'; });
  await page.click('#copy-iban .rs-copy__btn');
  st = await ev(() => { const c = document.getElementById('copy-iban'); return { state: c.dataset.state, msg: c.querySelector('.rs-copy__msg').textContent, hidden: c.querySelector('.rs-copy__msg').hidden }; });
  check('copy: 423 shows "Zwischenablage belegt – bitte nochmal klicken"', st.state === 'busy' && !st.hidden && st.msg === 'Zwischenablage belegt – bitte nochmal klicken', st);
  await page.click('#copy-iban .rs-copy__btn');
  st = await ev(() => { const c = document.getElementById('copy-iban'); return { state: c.dataset.state, hidden: c.querySelector('.rs-copy__msg').hidden, ev: window.__copyEv }; });
  check('copy: retry clears busy message', st.state === 'copied' && st.hidden, st);
  check('copy: rs-copy events', JSON.stringify(st.ev) === '[{"ok":true,"busy":false},{"ok":false,"busy":true},{"ok":true,"busy":false}]', st.ev);
  st = await ev(() => { const c = document.getElementById('copy-x'); return { hidden: c.querySelector('.rs-copy__value').hidden, label: c.querySelector('.rs-copy__label').textContent }; });
  check('copy: no-value hides the value box', st.hidden && st.label === 'Text kopieren', st);

  // rs-counter
  st = await ev(() => { const c = document.getElementById('counter-over'); return { over: c.over, num: c.querySelector('.rs-counter__num').textContent, extra: c.querySelector('.rs-counter__over').textContent, sr: c.querySelector('.rs-vh').textContent }; });
  check('counter: over state + accessible label', st.over && st.num === '301 / 280' && st.extra === '21 zu viel' && st.sr === '301 von 280 Zeichen, 21 zu viel', st);
  st = await ev(() => [...document.querySelectorAll('rs-counter[platform]')].map((c) => ({ p: c.getAttribute('platform'), k: c.getAttribute('kind') || 'chars', over: c.over, r: c.result })));
  const byP = Object.fromEntries(st.map((x) => [x.p + ':' + x.k, x]));
  check('counter: X composed text is over 280', byP['x:chars'].over && byP['x:chars'].r.count > 280, byP['x:chars']);
  check('counter: LinkedIn/Instagram/Facebook within limits', !byP['linkedin:chars'].over && !byP['instagram:chars'].over && !byP['facebook:chars'].over, st);
  check('counter: Instagram hashtags = 3', byP['instagram:hashtags'].r.hashtags === 3, byP['instagram:hashtags']);

  // rs-post-frame
  st = await ev(() => ['x', 'linkedin', 'instagram', 'facebook'].map((s) => {
    const f = document.querySelector(`rs-post-frame[skin="${s}"]`);
    const note = f.querySelector('.rs-pf__foldnote');
    const marker = f.querySelector('.rs-pf__fold');
    return { s, label: f.getAttribute('aria-label'), role: f.getAttribute('role'), platform: f.querySelector('.rs-pf__platform').textContent,
      note: note && !note.hidden ? note.textContent : null, marker: marker && !marker.hidden ? [marker.style.left, marker.style.top, marker.style.height] : null,
      logo: !!f.querySelector('svg.rs-pf-logo'), text: f.querySelector('[slot="text"]').textContent.length,
      img: !!f.querySelector('.rs-pf__media img'), empty: !!f.querySelector('.rs-pf__media--empty') };
  }));
  const pf = Object.fromEntries(st.map((x) => [x.s, x]));
  check('post-frame: group with "Vorschau <Plattform>" names', st.every((x) => x.role === 'group' && x.label === 'Vorschau ' + x.platform), st.map((x) => x.label));
  check('post-frame: inline SVG logo per skin', st.every((x) => x.logo));
  check('post-frame: LinkedIn fold guide at 210', pf.linkedin.note && pf.linkedin.note.includes('210') && pf.linkedin.marker, pf.linkedin);
  check('post-frame: Instagram fold guide at 125', pf.instagram.note && pf.instagram.note.includes('125') && pf.instagram.marker, pf.instagram);
  check('post-frame: no fold guide on X/Facebook', !pf.x.note && !pf.facebook.note, [pf.x.note, pf.facebook.note]);
  check('post-frame: Instagram without image shows the empty state', pf.instagram.empty && !pf.instagram.img, pf.instagram);
  st = await ev(() => {
    const out = {};
    for (const [k, h] of CSS.highlights) out[k] = h.size;
    return out;
  });
  check('post-frame: hashtag/link highlights registered', st['rs-pf-tag-x'] >= 3 && st['rs-pf-after-li'] === 1 && st['rs-pf-after-ig'] === 1, st);
  // live update: changing the slotted text re-decorates
  await ev(() => { document.querySelector('rs-post-frame[skin="linkedin"] [slot="text"]').textContent = 'kurz #a'; });
  await page.waitForTimeout(0);
  await page.clock.runFor(10);
  st = await ev(() => document.querySelector('rs-post-frame[skin="linkedin"] .rs-pf__foldnote').hidden);
  check('post-frame: text change below the fold hides the guide', st === true, st);
  // skin switch keeps slotted content
  st = await ev(() => { const f = document.getElementById('pf-fb'); f.setAttribute('skin', 'x'); const r = { name: f.querySelector('.rs-pf__name [slot="name"]')?.textContent, img: !!f.querySelector('.rs-pf__media img'), platform: f.querySelector('.rs-pf__platform').textContent }; f.setAttribute('skin', 'facebook'); return r; });
  check('post-frame: skin switch keeps slots', st.name === 'Northwind' && st.img && st.platform === 'X', st);

  // rs-confirm
  await page.focus('#copy-iban .rs-copy__btn');
  await ev(() => { window.__c = undefined; document.getElementById('kit-confirm').open({ word: 'LÖSCHEN' }).then((v) => { window.__c = v; }); });
  st = await ev(() => { const d = document.querySelector('#kit-confirm dialog'); return { open: d.open, modal: d.matches(':modal'), label: d.querySelector('label').textContent, focus: document.activeElement.className, disabled: d.querySelector('button[type=submit]').disabled }; });
  check('confirm: modal open, label text, focus in input, confirm disabled', st.open && st.modal && st.label === 'Zum Bestätigen „LÖSCHEN“ eintippen' && st.focus.includes('rs-confirm__input') && st.disabled, st);
  await page.keyboard.type('löschen');
  st = await ev(() => document.querySelector('#kit-confirm button[type=submit]').disabled);
  check('confirm: case differs -> still disabled', st === true);
  await page.keyboard.press('Enter');
  st = await ev(() => ({ open: document.querySelector('#kit-confirm dialog').open, c: window.__c }));
  check('confirm: Enter with wrong word does nothing', st.open && st.c === undefined, st);
  await page.fill('#kit-confirm input', 'LÖSCHEN ');
  st = await ev(() => document.querySelector('#kit-confirm button[type=submit]').disabled);
  check('confirm: trailing space -> still disabled (exact match)', st === true);
  await page.fill('#kit-confirm input', 'LÖSCHEN');
  st = await ev(() => document.querySelector('#kit-confirm button[type=submit]').disabled);
  check('confirm: exact word enables confirm', st === false);
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => window.__c !== undefined);
  st = await ev(() => ({ c: window.__c, open: document.querySelector('#kit-confirm dialog').open, focus: document.activeElement.closest('rs-copy')?.id }));
  check('confirm: resolves true, closes, returns focus', st.c === true && !st.open && st.focus === 'copy-iban', st);
  st = await ev(async () => {
    const c = document.createElement('rs-confirm');
    const p = c.open({ word: 'JA' });
    const attached = c.isConnected;
    c.querySelector('.rs-btn--secondary').click();
    return { attached, result: await p, after: c.isConnected };
  });
  check('confirm: detached element attaches itself and cleans up; Abbrechen -> false', st.attached && st.result === false && !st.after, st);

  // global a11y basics
  st = await ev(() => ({
    pos: [...document.querySelectorAll('[tabindex]')].filter((e) => e.tabIndex > 0).length,
    unnamed: [...document.querySelectorAll('button, input, textarea, select')].filter((e) => {
      if (e.closest('dialog:not([open])')) return false;
      const name = (e.getAttribute('aria-label') || e.labels?.[0]?.textContent || e.innerText || e.placeholder || '').trim();
      return !name;
    }).map((e) => e.outerHTML.slice(0, 80)),
  }));
  check('no positive tabindex', st.pos === 0, st.pos);
  check('every control has a name', st.unnamed.length === 0, st.unnamed);
  await ctx.close();
}

await browser.close();

if (checks) {
  let fail = 0;
  for (const c of checks) {
    if (!c.ok) fail++;
    console.log((c.ok ? 'PASS ' : 'FAIL ') + c.name + (c.ok ? '' : '  ' + JSON.stringify(c.info)));
  }
  console.log(`\n${checks.length - fail}/${checks.length} checks passed`);
  console.log('screenshots: ' + outDir);
  process.exit(fail ? 1 : 0);
}
