"""Writes core/static/icons/icon.svg from the shipped blob avatar shape.

The app icon is the default bot look: a white blob with two dark eyes on a
dark rounded tile. The blob outline comes from core/static/avatar-shapes.json
(the same shape the avatars use); the eyes sit where the shape's eyes are,
drawn a little larger; icon-small.svg (used for the 16/32 px renders) sets\nthem nearer the middle, apart and upright so they stay two eyes at 16 px.
Usage: python tools/dev/make-icon-svg.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SHAPES = json.loads((ROOT / "core" / "static" / "avatar-shapes.json").read_text(encoding="utf-8"))
TILE = "#111111"
BLOB = "#ffffff"
EYE_SCALE = (1.15, 1.6)  # along / across the eye (main icon)
SMALL = {"scale": (1.2, 1.7), "spread": 1.15, "rotate": 80, "inward": 0.45}  # 16/32 px variant: eyes apart, upright


def eyes(path):
    """Centre, radii and rotation of each elliptical eye hole in the path."""
    found = []
    for m in re.finditer(r"M([\d.]+) ([\d.]+)A([\d.]+) ([\d.]+) ([\d.]+) 1 0 ([\d.]+) ([\d.]+)", path):
        x1, y1, rx, ry, rot, x2, y2 = map(float, m.groups())
        found.append(((x1 + x2) / 2, (y1 + y2) / 2, rx, ry, rot))
    return found


def build(name, eye_scale, spread=1.0, rotate=None, inward=0.0):
    blob = SHAPES["shapes"]["blob"]
    outline = blob.split("Z")[0] + "Z"
    lo, hi = 1.5, 46.5
    scale = 46 / (hi - lo)
    shift = 32 - 24 * scale
    parts = []
    found = eyes(blob)
    mx = sum(e[0] for e in found) / len(found)
    my = sum(e[1] for e in found) / len(found)
    tx, ty = mx + (24 - mx) * inward, my + (24 - my) * inward  # eyes nearer the middle
    for cx, cy, rx, ry, rot in found:
        cx, cy = tx + (cx - mx) * spread, ty + (cy - my) * spread
        rot = rot if rotate is None else rotate
        parts.append(
            f'<ellipse cx="{cx:.2f}" cy="{cy:.2f}" rx="{rx * eye_scale[0]:.2f}" '
            f'ry="{ry * eye_scale[1]:.2f}" transform="rotate({rot:g} {cx:.2f} {cy:.2f})" fill="{TILE}"/>'
        )
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">\n'
        '  <!-- grokbot-desk app icon: the shipped blob avatar shape (white, dark eyes)\n'
        '       on a dark rounded tile; generated by tools/dev/make-icon-svg.py -->\n'
        f'  <rect width="64" height="64" rx="14" fill="{TILE}"/>\n'
        f'  <g transform="translate({shift:.3f} {shift:.3f}) scale({scale:.4f})">\n'
        f'    <path d="{outline}" fill="{BLOB}"/>\n'
        + "".join(f"    {p}\n" for p in parts)
        + "  </g>\n</svg>\n"
    )
    (ROOT / "core" / "static" / "icons" / name).write_text(svg, encoding="utf-8", newline="\n")
    print(name, len(parts), "eyes")


def main():
    build("icon.svg", EYE_SCALE)
    build("icon-small.svg", SMALL["scale"], SMALL["spread"], SMALL["rotate"], SMALL["inward"])


if __name__ == "__main__":
    main()
